name: publish

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * MON"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define image tag
        run: date -u +"%Y-%m-%d-%H-%M-%S" > tag

      - name: Docker Build
        run: docker build . --tag ghcr.io/cubos/remote-images-${{ matrix.image }}:$(cat ../tag)  --pull
        working-directory: ${{ matrix.image }}

      - name: Docker Push
        run: docker push ghcr.io/cubos/remote-images-${{ matrix.image }}:$(cat tag)

      - name: Update README.md
        run: |
          git pull

          docker run -v $GITHUB_WORKSPACE:/work ghcr.io/cubos/remote-images-${{ matrix.image }}:$(cat tag) bash -c "cd /work/${{ matrix.image }}; ./update-readme.sh"

          [ -z "$(git diff README.md)" ] && exit

          UPDATED_PACKAGES=$(
            git diff README.md |
            grep "^+|" |
            cut -d'|' -f 2 |
            grep -v -- "----" |
            grep -v Name |
            sed 's/^ *//;s/ *$//' |
            head -c -1 |
            tr '\n' ',' |
            sed -e 's/,/, /g'
          )

          git config --global user.name ci
          git config --global user.email ci@example.com
          git add README.md
          git commit -m "update $IMAGE: $UPDATED_PACKAGES"

          git push origin main
